<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php 
                         
                         
                         
                        if (session_status()==PHP_SESSION_NONE) { 
                            session_start();
                              
                        }
                        
                        
                        if (isset($_SESSION['user'])){
                                echo "<li class='active'><a href='" . $this->url('home') . "'>" . $this->translate('Home') . "</a></li>";
                                echo "<li class='active'><a href='/application/user/profil'>" . $this->translate('Profil') . "</a></li>";
                                echo "<li class='active'><a href='/application/annonce/index'>" . $this->translate('Mes Annonces') . "</a></li>";
                                echo "<p id='floatRight'> <span>Bonjour, " . $_SESSION['user']['Prenom'] . " </span>";
                                echo "<a href='/application/user/deconnect'>" . $this->translate('Se déconnecter') . "</a></p>";
                            
                        }
                        else {
                            echo "<li class='active'><a href='" . $this->url('home') . "'>" . $this->translate('Home') . "</a></li>";
                            echo "<li class='active'><a href='/application/user/index'>" . $this->translate('Compte') . "</a></li>";
                        }
                        
                        ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; 
            
            ?>
            <hr>
            <footer id="clearFloat">
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
