<h1>Compte</h1> <br> <br>
<table class="userForm">
            <tr>
                <td><h4>Log In</h4></td>
                <td rowspan="2" class="orBetween"><h4>Ou</h4></td>
                <td><h4>Créer un compte</h4></td>
            </tr>
            <tr>
                <td>
                    <form action="connexion" method="post" id="formChanger">
                        <label>Email:</label> <input type="text" name="email" class="email"><br><br>
                        <label>Mot de Passe:</label> <input type="password" name="password" class="password"><br><br>
                        <input type="submit" value="Connectez-vous">
                    </form>
                </td>
                <td>
                    <form action="inscription" method="post" id="formChanger"><br>
                        <label>Nom:</label> <input type="text" name="nom" class="nom"><br><br>
                        <label>Prénom:</label> <input type="text" name="prenom" class="prenom"><br><br>
                        <label>Email:</label> <input type="email" name="email" class="email"><br><br>
                        <label>Téléphone:</label> <input type="text" name="telephone" class="telephone"><br><br>
                        <label>Adresse:</label> <input type="text" name="adresse" class="adresse"><br><br>
                        <label>Mot de Passe:</label> <input type="password" name="password" class="password"><br><br>
                        <input type="submit" value="Inscriez-vous"><br><br>
                    </form>
                </td>
            </tr>
</table>